-- AlterTable
ALTER TABLE "ServiceOrder" ADD COLUMN     "deviceImages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "defects" DROP NOT NULL,
ALTER COLUMN "aparelho" DROP NOT NULL,
ALTER COLUMN "cep" DROP NOT NULL;
